<?php
$YaURLLink=$URL_2ya[0];
$YaURLLink.=$TempArr_coord;
$YaURLLink.=$URL_2ya[1];
$YaURLLink.=$URL_2ya[2];
$YaURLLink.=$URL_2ya[3];
$YaURLLink.=$TempYaArr_coord;
$YaURLLink.=$URL_2ya[4];
$YaURLLink.=$TempArr_coord;
?>